SET PAGESIZE 100;
SET LINESIZE 200;
SET ECHO OFF;
SET FEEDBACK OFF;

PROMPT ==================== USERS TABLE DATA ====================
PROMPT 

COLUMN ID FORMAT 9999;
COLUMN FULL_NAME FORMAT A30;
COLUMN EMAIL FORMAT A40;
COLUMN PHONE FORMAT A15;
COLUMN ADDRESS FORMAT A40;
COLUMN HOUSE_NO FORMAT A15;
COLUMN WARD_NO FORMAT 999;
COLUMN WARD_ZONE FORMAT A10;
COLUMN PASSWORD FORMAT A20;
COLUMN CREATED_AT FORMAT A30;

SELECT ID, FULL_NAME, EMAIL, PHONE, PASSWORD, ADDRESS, HOUSE_NO, WARD_NO, WARD_ZONE, CREATED_AT 
FROM users 
ORDER BY ID DESC;

PROMPT 
PROMPT ==================== USER COUNT ====================
SELECT COUNT(*) as TOTAL_USERS FROM users;

PROMPT 
PROMPT ==================== RAW FORMAT ====================
SELECT * FROM users;

EXIT;
